import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';

const initialState = {
    isAuthenticated: false,
    isLoading: true,
    user: {
        "email": "",
        "phone": "",
        "fullName": "",
        "role": "",
        "avatar": "",
        "id": ""
    },

};

export const accountSlice = createSlice({
    name: 'account',
    initialState,

    //Khởi tạo 2 actions (doLoginAction và doGetAccountAction) dùng để nạp data vào Redux
    //Reducer: Xử lý dữ liệu của Redux sau đấy lưu dữ liệu vào State(Redux)
    reducers: {
        //Nhận vào 2 tham số:
        //1: state: Trạng thái của redux - Nơi lưu trữ data của Redux (Khác vs state của React)
        //2: action: từ phía React (Home.js) thì truyền action lên ntn
        doLoginAction: (state, action) => {

            // Khi tạo action của Redux muốn nạp dữ liệu từ action vào trong Redux Store(Store: Nơi lưu trữ dữ liệu của Redux)
            state.isAuthenticated = true;
            //action sẽ lấy dc payload sau đó gán vào state của Redux
            state.user = action.payload;

            //video 28 - chapter 1
            //Khi đăng nhập thành công thì sẽ ko có trạng thái loading nữa
            state.isLoading = false;
        },

        doGetAccountAction: (state, action) => {
            state.isAuthenticated = true;
            state.user = action.payload;

            state.isLoading = false;
        },

        doLogoutAction: (state, action) => {
            localStorage.removeItem('access_token');
            state.isAuthenticated = false;
            state.user = {
                email: "",
                phone: "",
                fullName: "",
                role: "",
                avatar: "",
                id: "",
            };
        },

    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {

    },
});

//Khi export 'doLoginAction' vs 'doGetAccountAction' thì sẽ gọi dc tới action này từ bên trong component của React
export const { doLoginAction, doGetAccountAction, doLogoutAction } = accountSlice.actions;

export default accountSlice.reducer;
